---
- name: check file/dir status
  stat:
    path: "{{ item }}"
  register: at_check

- set_fact:
    at_status_msg: "{{ item }} status ERROR"

- set_fact:
    at_status_msg: "{{ item }} Not Present/OK"
  when: not at_check.stat.exists

- set_fact:
    at_status_msg: "{{ item }} status OK"
  when: >
    at_check.stat.mode is defined
    and at_check.stat.mode == at_files_status.mode
    and at_check.stat.gr_name == at_files_status.group
    and at_check.stat.pw_name == at_files_status.owner

- debug:
    msg: "Result test of: {{ at_status_msg }}"
