---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Include role vars
      include_vars: ../../vars/main.yml

    - name: Read at config files
      stat:
        path: "{{ item }}"
      loop: "{{ at_files }}"
      register: check_files_result

    - name: Assert that permissions are correct
      assert:
        that:
          - check_files_result.results[index].stat.mode == at_mode
          - check_files_result.results[index].stat.gr_name == at_group
          - check_files_result.results[index].stat.pw_name == at_owner
      when: check_files_result.results[index].stat.mode is defined
      loop: "{{ at_files }}"
      loop_control:
        index_var: index

    - name: Read /etc/at.allow file
      command: cat /etc/at.allow
      register: read_at_allow_result
      changed_when: no

    - name: Read /etc/at.deny file
      command: cat /etc/at.deny
      register: read_at_deny_result
      changed_when: no

    - name: Assert at.allow and at.deny files are correct
      assert:
        that:
          - read_at_allow_result.stdout is search("root")
          - read_at_deny_result.stdout is search("nobody")
